using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SistemaEtiquetas.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class MigrateToPostgres : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Convert DateTime TEXT columns to timestamp with time zone
            migrationBuilder.Sql(
                @"ALTER TABLE ""Pedidos"" 
                  ALTER COLUMN ""DataPedido"" TYPE timestamp with time zone USING ""DataPedido""::timestamp with time zone;");

            migrationBuilder.Sql(
                @"ALTER TABLE ""Pedidos"" 
                  ALTER COLUMN ""DataCriacao"" TYPE timestamp with time zone USING ""DataCriacao""::timestamp with time zone;");

            // Convert INTEGER boolean columns to proper boolean type
            migrationBuilder.Sql(
                @"ALTER TABLE ""PedidoItens"" 
                  ALTER COLUMN ""Impresso"" DROP DEFAULT;
                  ALTER TABLE ""PedidoItens"" 
                  ALTER COLUMN ""Impresso"" TYPE boolean USING ""Impresso""::boolean;
                  ALTER TABLE ""PedidoItens"" 
                  ALTER COLUMN ""Impresso"" SET DEFAULT false;");

            migrationBuilder.Sql(
                @"ALTER TABLE ""PedidoItens"" 
                  ALTER COLUMN ""Erro"" DROP DEFAULT;
                  ALTER TABLE ""PedidoItens"" 
                  ALTER COLUMN ""Erro"" TYPE boolean USING ""Erro""::boolean;
                  ALTER TABLE ""PedidoItens"" 
                  ALTER COLUMN ""Erro"" SET DEFAULT false;");

            // Convert TokenExpiration TEXT to timestamp with time zone
            migrationBuilder.Sql(
                @"ALTER TABLE ""Configuracoes"" 
                  ALTER COLUMN ""TokenExpiration"" TYPE timestamp with time zone USING ""TokenExpiration""::timestamp with time zone;");

            // Set up identity generation for Postgres on all Id columns
            migrationBuilder.Sql(
                @"ALTER TABLE ""Pedidos"" 
                  ALTER COLUMN ""Id"" TYPE integer;
                  ALTER TABLE ""Pedidos"" 
                  ALTER COLUMN ""Id"" DROP DEFAULT;
                  ALTER TABLE ""Pedidos"" 
                  ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;");

            migrationBuilder.Sql(
                @"ALTER TABLE ""PedidoItens"" 
                  ALTER COLUMN ""Id"" TYPE integer;
                  ALTER TABLE ""PedidoItens"" 
                  ALTER COLUMN ""Id"" DROP DEFAULT;
                  ALTER TABLE ""PedidoItens"" 
                  ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;");

            migrationBuilder.Sql(
                @"ALTER TABLE ""Configuracoes"" 
                  ALTER COLUMN ""Id"" TYPE integer;
                  ALTER TABLE ""Configuracoes"" 
                  ALTER COLUMN ""Id"" DROP DEFAULT;
                  ALTER TABLE ""Configuracoes"" 
                  ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Reverse migrations would go here if needed
        }
    }
}
